version: '3'
services:
  shorten-url:
    build: .
    command: npm run start:dev 
    ports:
      - "${ENV_NODE_PORT}:${ENV_NODE_PORT}"
    depends_on:
      - shorten-url-db
    environment:
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_HOST=db
      - DATABASE_DATABASE=${DATABASE_DATABASE}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_SSL=${DATABASE_SSL}
    volumes:
      - ./src:/usr/src/app/src  # Sync the src directory
      - ./node_modules:/usr/src/app/node_modules  # Sync the node_modules directory
    env_file:
      - .env
  shorten-url-db:
    image: postgres
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_DATABASE}
    ports:
      - "${DATABASE_PORT}:5432"
    env_file:
      - .env

